name: Deploy to Development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ensure known_hosts file exists
        run: touch ~/.ssh/known_hosts

      - name: Remove old host key
        run: ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "${{ secrets.DO_HOST }}"

      - name: Add new host key
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Verify SSH Key and Connection
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${DO_USER}@${DO_HOST} "echo 'SSH connection established'"

      - name: Debug SSH Key
        run: |
          ssh-keygen -lf ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} > /dev/null

      - name: Run update script on DigitalOcean Droplet
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${DO_USER}@${DO_HOST} << EOF
          sudo -i -u matt bash << EEOF
          cd ~/LibreChat && \
          git fetch origin main && \
          npm run update:deployed && \
          git checkout do-deploy && \
          git rebase main && \
          npm run start:deployed && \
          echo "Update completed. Application should be running now."
          EEOF
          EOF